const home = require('./routes/home');
const login = require('./routes/login');
const browse = require('./routes/browse');
const about = require('./routes/about');
const register = require('./routes/register');
const dashboard = require('./routes/dashboard');
const comments = require('./routes/comments');
const success = require('./routes/success');
const image = require('./routes/image');
const logout = require('./routes/logout');
const express = require('express');
const nsfw = require('./routes/nsfw');
const reports = require('./routes/reports');
const registry = require('./routes/registry');
const applicants = require('./routes/applicants');
const logs = require('./routes/logs');
const comment = require('./routes/comment');
const images = require('./routes/images');
const forgotPassword = require('./routes/forgotPassword');
const passwordReset = require('./routes/passwordReset');
const reset = require('./routes/reset');
const bernard = require('./routes/bernard');
const games = require('./routes/games');
const router = express.Router();

router.use('/', home);
router.use('/login', login);
router.use('/browse', browse);
router.use('/about', about);
router.use('/register', register);
router.use('/dashboard', dashboard);
router.use('/comments', comments);
router.use('/success', success);
router.use('/image', image);
router.use('/logout', logout);
router.use('/nsfw', nsfw);
router.use('/reports', reports);
router.use('/registry', registry);
router.use('/applicants', applicants);
router.use('/logs', logs);
router.use('/comment', comment);
router.use('/images', images);
router.use('/forgotPassword', forgotPassword);
router.use('/passwordReset', passwordReset);
router.use('/reset', reset);
router.use('/bernard', bernard);
router.use('/games', games);

module.exports = router;
